### ISSUE TITLE
Initialization option "create section" not working

### ISSUE THREAD

**Issue by aleksa9275** [nextfoam/baram#107]
Hello,

I'm testing Baram for ship resistance calculations. I have found that I cannot follow the flow tutorial. When setting up the KCS flow I cannot create the water part of the region using the instructions from the tutorial.

I'm using Baram 24.3.1 for windows. On the below screenshot clicking the "OK" button does nothing, the only thing that can be done is "Cancel" or "X".

![Screenshot_2](https://github.com/user-attachments/assets/1ef272f5-6568-4e62-bcde-15256e1a6c89)

If there is something I'm missing, like creating a mesh in a different way or setting up flow differently please let me know. I hope this comes down to refreshing the tutorial page, hopefully adding the KCS mesh tutorial as well as updating the KCS flow tutorial.

If I can contribute in any way by testing Baram mesh and flow I'll be more than happy to help.

Best regards,
Aleksa

**Comment by jiban** [comment]
Hi, Aleksa.
Unfortunately v24.3.1 has an issue handling volume fraction configuration in section initialization as you may see in [the release note](https://baramcfd.org/docs/release_notes/#known-issues).

![image](https://github.com/user-attachments/assets/d469c4cd-e796-4024-bdb0-23522ddeb2c7)

Please wait for v24.3.2 that will be released in a few days.
Thank you.

Best regards,
Jake

**Comment by aleksa9275** [comment]
Hi Jake,

I'm sorry for this oversight.

Thank you for your great work on making cfd user friendly. 

Best regards,
Aleksa

**Comment by jiban** [comment]
Hi Aleksa,
BARAM v24.3.2, which has fix for this issue, has released just now.
You can download it on [baramCFD](https://baramcfd.org/) page as usual.

**Comment by aleksa9275** [comment]
Creating sections now works, calculation runs properly.

Thanks.
