### ISSUE TITLE
Missing PyQt5.QtCore in baram-24.3.3 apptainer

### ISSUE THREAD

**Issue by H2Birk** [nextfoam/baram#120]
First of all, I want to appreciate your great work. Your GUI is a real enrichment for OpenFoam.

Now to the issue:

	* The apptainer baram-24.3.3-apptainer.tar.gz has been downloaded and extracted
	* chmod +x install.sh
	* ./install.sh
	* $MyInstallationPath$
	
If I now want to start Baram via:

	apptainer exec $MyInstallationPath$/baram-24.3.3.sif bash -c '/opt/baram/baramMesh.sh'
	
the following error appears:

	Traceback (most recent call last):
	  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
	    return _run_code(code, main_globals, None,
	  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
	    exec(code, run_globals)
	  File "/opt/baram/baramMesh/main.py", line 9, in <module>
	    import qasync
	  File "/usr/local/lib/python3.10/dist-packages/qasync/__init__.py", line 85, in 			<module>
	    QtCore = importlib.import_module(QtModuleName + ".QtCore", package=QtModuleName)
	  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
	    return _bootstrap._gcd_import(name[level:], package, level)
	ModuleNotFoundError: No module named 'PyQt5.QtCore'
	
Which is odd, since everything needed should be in a container so it can run out of the box.
It would be helpful to know if this is a user error on my part or if there is indeed a missing module in the container.

My system is as follows:

	Operating System: TUXEDO OS 3
	KDE Plasma Version: 6.1.5
	KDE Frameworks Version: 6.5.0
	Qt Version: 6.7.2
	Kernel Version: 6.11.0-102007-tuxedo (64-bit)
	Graphics Platform: X11
	
Best regards

**Comment by kdg5424** [comment]
Hello @H2Birk. This is Donggyu Kim from NEXTFOAM.

We're not supporting apptainer right now and TUXED OS also.
Could you try with compiled?

Thanks

Best regards

Donggyu Kim

**Comment by H2Birk** [comment]
Hello Donggyu,

Thank you for your reply. Since Tuxedo is Ubuntu-based, it works fine with software made for Ubuntu. For example, the classic OpenFoam works without errors.

I have tried compiling Baram from source, but I am stuck with an error while compiling nextfoam-cfd. Since I don't have to use Baram right now, this doesn't need to bother you.

It is really unfortunate that a container solution isn't supported at the moment, but perhaps it will be again in the future.
This would make the installation of Baram much more user-friendly.

I am looking forward to the future of Baram/NEXTFOAM!

Best regards
H2Birk

**Comment by kdg5424** [comment]
Hello @H2Birk. Could you let me know what is the problem while you compiled nextfoam-cfd source?
If your OS is based on Ubuntu, then there should be no problem. We already tested and compiled on Ubuntu 20.04 and Ubuntu 22.04.
If you let me know your problem, maybe we can help you.

Best Regards

Donggyu Kim

**Comment by H2Birk** [comment]
Hello Donggyu,

Thank you for your offer. I retried compiling nextfoam-cfd using a different approach:

**The previous Problem**

When compiling in the "/opt/" directory, as described in the guide, a paradox occurs:

If running

`./Allwmake -j`

there is no permission to create new entities.

Running "Allwmake" as root via sudo gives the following error:

`Error (Allwmake) : not located in $WM_PROJECT_DIR
    Check your OpenFOAM environment and installation`

When I checked the path of $WM_PROJECT_DIR, it was correct: _/opt/OpenFOAM/NextFOAM-2409._

So in summary: Allwmake doesn't work correctly if executed as root, but without, it is has no permissions for writing.

**My solution**

I compiled evertything into a home-folder, where no root-permission is required. Now the compiling works, but it literally takes hours.

After that, I continued installing Baram, again without root permissions.

**A new problem**

Unfortunately, I still can't open baramMesh/Flow. When executing the .sh files, I get the following error for baramMesh.sh:

`QSocketNotifier: Can only be used with threads started with QThread
QWidget: Must construct a QApplication before a QWidget`

for baramMesh.sh

And for baramFlow:

`QSocketNotifier: Can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
`

Please feel free to take your time with this issue, as it isn't urgent at all.

I would still **highly** recommend a container solution for a more robust and reliable software experience.


Best regards
H2Birk

**Comment by kdg5424** [comment]
Hello @H2Birk.
It looks like you tried lots of.
The problem : `QSocketNotifier: Can only be used with threads started with QThread QObject::startTimer: Timers can only be used with threads started with QThread ` might happen because of QT.

I'll discuss with our developers for the container or other support platforms for the linux users.

Thanks

Best regards
Donggyu Kim

**Comment by H2Birk** [comment]
Hello Donggyu,

I've heard that Qt can sometimes be a bit tricky, but I don't have the necessary knowledge in this area.

I truly appreciate your support. Such excellent service is uncommon, even among large commercial companies (I can say that from my own experience).

This is why NextFOAM/Baram is such a valuable asset to the CFD community.

I wish you and your team all the best.

With kind regards
H2Birk

**Comment by kdg5424** [comment]
Hello @H2Birk. This is Donggyu from NEXTFOAM.
I'm very glad to hear that you like BARAM very much.

For the QT problem, could  you try Paraview on your machine?
And please let me know whether Paraview operates well.

Thank you very much.

Best regards

Donggyu Kim

**Comment by H2Birk** [comment]
Hello Donggyu,

ParaView was installed via https://www.paraview.org/download/ (ParaView-5.13.1-MPI-Linux-Python3.10-x86_64). 
As you can see in the attached image, it works without errors.

Installing ParaView via "apt" also works, but it is an older version (5.10).

But since you asked if ParaView works: 
Could it be that Baram depends on the Qt version of ParaView? 
Since I didn’t install Baram as intended into the /opt/ path (due to the issue with root permissions), could it be that the path where Baram expects ParaView (and its Qt) is incorrect and has to be changed manually?

Or is a separate version of ParaView located in the "ThirdParty" directory?

Thank you so much for your previous help!


Best regards
H2Birk

![Paraview_20241010_132022](https://github.com/user-attachments/assets/a4a3e8ea-2c82-47fc-b2e1-377cfa2e5c2d)

**Comment by kdg5424** [comment]
Hello @H2Birk. It's really weird. Because if Paraview runs well, there should be no problem with BARAM. Becaus your QT is no problem.
Before I discuss with @jiban, I recommend you to input on terminal this simple code.
`QT_QPA_PLATFORM=xcb`
I'll let you know after discussion with @jiban.

Thanks

Best regards

Donggyu Kim

**Comment by kdg5424** [comment]
Hello @H2Birk. This is Donggyu from NEXTFOAM.

I discussed with @jiban. And we decieded to send you the compressed BARAM file (I mean .tar file).
The size of the compressed file is too large, so you can download it from our google drive.
After uncompress it, I wish you to use it.

You can try it with this commmand : `./BaramFlow` or `./BaramMesh` in BARAM folder.
And try the command that I told you : `QT_QPA_PLATFORM=xcb`

Google Drive Link : [BARAM Compressed file](https://drive.google.com/file/d/1XFVm421-IG4GD-o8VdIY5ono1UCooQzj/view?usp=sharing)

Thank you

Best regards

Donggyu Kim

**Comment by H2Birk** [comment]
Hello Donggyu,

Thank you for your quick response.

The suggested code `QT_QPA_PLATFORM=xcb` didn't work, but the compressed file did the trick. (Although Wayland isn’t supported, that’s not a big deal.) 
As is often the case, the problem was likely in front of the computer. Something probably went wrong during compilation.

For validation, I followed the Mixing Pipe tutorial on your website. Even though it was in Korean, translation via DeepL and the clear images made it easy to follow.

I’m really impressed by the ease of use of Baram and, even more so, by your excellent support. **Thank you very much for your time!** Good customer support is something many large companies tend to neglect these days, but it’s clearly a strong point for you. 
Knowing that I can rely on your commercial solutions in the future is a big plus.

Additionally, I’d like to show Baram to my former CFD professor, who is a fan of OpenFoam. Given OpenFoam’s steep learning curve and the fact that it requires Linux (while most people still use Windows), Baram could be a great alternative to a certain other software starting with "A"—from which we currently have a "cheap" license.

If our students run into issues, I’ll tell them to come to me first to avoid overwhelming your support team.

If there are no further questions, this issue can be considered resolved.

Best regards,
H2Birk

BaramMesh:
![BaramMesh_Tuto_1](https://github.com/user-attachments/assets/53533b21-1adb-4978-a72b-68bcb96a1c96)

BaramFlow:
![BaramFlow_Tuto_1](https://github.com/user-attachments/assets/8475a5b6-fda5-429b-ba63-6bc7d41354c4)

Postprocessing:
![BaramPost_Tuto_1](https://github.com/user-attachments/assets/c71e723e-eaa9-45e2-85f6-fd92a038ac09)

**Comment by kdg5424** [comment]
Hello @H2Birk.

It's my big pleasure that you solve your problem. We always try to make "CFD for Everyone and Everywhere!" - It's our slogan.

If you have any issue with BARAM, please don't hesitate to inqury.
We're always welcome to assist and support our clients / customers.

And I hope you use BARAM well.

Thanks.

Best regards

Donggyu Kim

**Comment by H2Birk** [comment]
Hello Donggyu,

Thank you for your kind message and for providing such excellent support.

As the issue has been resolved with your assistance, I am going to close this section now.

Best wishes to you and the Nextfoam/BARAM team.

**Comment by nihataksu** [comment]
Hello @kdg5424 and @H2Birk,

I am working on an exact, reproducible rerun of the official BARAM KCS resistance tutorial. The archived case stdout identifies the required Linux solver as:

`2d26db97-20240705 OPENFOAM=2312 version=v2312`

Historical BARAM publication pages reference two likely carriers:

- `solvers_linux_24.3.0_20240726.tar.xz` (the CloudFront object now returns HTTP 403)
- `baram-24.3.3-apptainer.tar.gz` (the historical OneDrive folder is now expired or permission-restricted)

We downloaded and inspected the surviving `BARAM-24.4.0.tar.xz` from this issue, but its `libOpenFOAM.so` identifies the newer build `c897e9d1-20240920`, so it cannot be used as the exact environment.

If either of you still has the original 24.3 solver bundle or Apptainer archive, would you be willing to restore access or provide a retained copy? A SHA-256, byte count, and confirmation of the build string would also be valuable. The payload will remain external to our repository and will be used only for reproducibility; we will not redistribute it.

Thank you.
