### ISSUE TITLE
Mesh generation failed

### ISSUE THREAD

**Issue by onuno7** [nextfoam/baram#134]
Hi,

I am new to Baram and CFD and while going through first tutorial, Mixing Pipe, can't pass Base Grid step since the error "Mesh Generation Failed" appears. Tried several times and always the same.

I use a Mac M1 with Sequoia 15.0.1.

Can you please help since I don't know if I am doing something wrong.

Here goes the message in the Console tab:

/*---------------------------------------------------------------------------*\
fileName::stripInvalid() called for invalid fileName /Users/cristinagomes/Documents/Baram-Nuno/mixing_pipe/case
| =========                 |                                                 |
    For debug level (= 2) > 1 this is considered fatal
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |

|  \\    /   O peration     | Version:  2312                                  |
|   \\  /    A nd           | Website:  www.openfoam.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : 64aabda6-20240924 OPENFOAM=2312 version=v2312
Arch   : "LSB;label=32;scalar=64"
Exec   : /Applications/BaramMesh.app/Contents/Frameworks/solvers/openfoam/bin/blockMesh
Date   : Oct 22 2024
Time   : 17:07:51
Host   : MacBook-Pro-de-Cristina.local
PID    : 13146
--> FOAM Warning :
    From Foam::fileName Foam::cwd_L()
    in file POSIX.C at line 513
    PWD is invalid - reverting to physical description

Thanks

**Comment by kdg5424** [comment]
Hello @onuno7. This is Donggyu from NEXTFOAM.

In log, there is a comment like this : "PWD is invalid - reverting to physical description"
It means PWD, the path of the project is invalid.
I think there is something wrong or problem with your path of project.
Could you let me know your path of the project or move it?

Best regards

Donggyu Kim

**Comment by onuno7** [comment]
Don't know what did wrong but, following what you mentioned, created a new folder and started again. It was just fine and could finish all steps. Thanks

**Comment by kdg5424** [comment]
I'm glad to hear that.
I think the path of the project and directory was something wrong.

Best regards

Donggyu Kim

**Comment by onuno7** [comment]
I think I might have changed the name of the folder afterwards and wasn't aware it would have this result or that the alert shown was related to that.
All good now.
Thanks
