### ISSUE TITLE
The solver failed to start in Version 24.4 windows

### ISSUE THREAD

**Issue by wkholy** [nextfoam/baram#141]
I recently install the new version 24.4 in windows 11. supersonic nozzle case from the tutorial is set for computation. The mesh import and settings are working fine. However, the solver failed to start when I click the "start calculation" button. No log file is outputed with an error of "the application cannot start normally(0xc0000142)"

When I go to the solver directory, try to run the solver and get the following error. May I ask if there will need additional setting in windows for of solvers ? 
\AppData\Local\Programs\Baram\solvers\openfoam\bin>TSLAeroFoam.exe
--> FOAM FATAL ERROR :
    Could not find mandatory etc entry (mode=ugo)
    'controlDict'
Thanks.

**Comment by wkholy** [comment]
Copy dll in the mingw directory into openfoam solver folder can solve the problem.

**Comment by kdg5424** [comment]
Hello @wkholy. This is Donggyu from NEXTFOAM.
Thank you for your interest in BARAM. And sorry for the inconvenience.
We'll update the page soon. There will be "English" manual soon.

Best regards

Donggyu Kim
