### ISSUE TITLE
Typo and minor bugs

### ISSUE THREAD

**Issue by samc99us** [nextfoam/baram#145]
There is a typo in BaramFlow 2.4.4.0. When opening a new file, a wizard shows up, requesting a "project directory". Below that, "project" is mis-spelled "projet"

Additionally, during case decomposition in baramFlow, i.e converting to parallel processing, the dialog box for tat process is hidden behind the parallel environment box, it should be in front.

![image](https://github.com/user-attachments/assets/684d6ef9-5d11-487f-81a5-71eee7fdaa52)

**Comment by jiban** [comment]
Hi, Sam.
Thank you for letting us know about that.
I've fixed it right away, and it will be included in the next release.
Have a nice weekend!

-- Jake
