### ISSUE TITLE
Installation intructions | Suggestions

### ISSUE THREAD

**Issue by Ricky-Tigg** [nextfoam/baram#22]
**kernel v.:** 6.0 | **distribution:** Fedora | **baram v.**: 22.0.4

Hello. The [installation intructions](https://nextfoam.github.io/baram-pages/docs/installation/) are solely documented outside this repository, and that without informing of its existence via a dedicated link to that site. Therefore the presence [here](https://github.com/nextfoam/baram) within section _About_ of a link accordingly to that page would be appropriate; now by default filled as _No description, website, or topics provided_.

As per those instructions covering Unix/Linux, i was able to run the application successfully, on X.org, with perfect window management, on Wayland server, which is served by Mutter in my user session, with nearly perfect window management. That is traditional.

Observations in respect to installation instructions:

- _CentOS 8.2 or newer_ as supported platforms. | Nowadays the **counterparts** of the traditional releases of CentOS are Rocky Linux and AlmaLinux. Development of traditional releases of CentOS was dully ceased by action of IBM via its company Red Hat. | Suggestion: _Rocky Linux and AlmaLinux in version 9.0 (for example) or newer_.
- `python3.9 -m venv venv` for the set-up of a virtual environment for Python |It appears that version 3.9 and newer are supported as i was able to run `python3.11 -m venv venv` successfully. | Suggestion: _Python **3.9 or newer** is required_ to replace _Python **3.9.x** is required_.
- _uncompress solver executables_ | It appears to be a partial instruction. Observing it would lead to insert a folder named `solvers_linux_[version_number]` into the suggested destination, which would result in a non-found resource when attempting to compile the daemon. | Suggestion: _Once the archive is uncompressed locate the folder `solvers `and place it into the top (...)_.

**Comment by jiban** [comment]
Dear Ricky,
Thank you for the careful and detailed description.
I've updated _About_ section as you kindly guided.

And for the installation instructions,

* Though I have no experience in _Rocky Linux_ and _AlmaLinux_, BARAM may work on them because the only critical limitation comes from QT6 that requires GLIBC(>=2.28).

* Actually it was _**Python 3.9 or newer**_ but changed to _**Python 3.9.x**_ specifically because vtk 9.1.0 does not support python 3.10 and above. This can be fixed if _requirements.txt_ is modified. You might have done it already.  I will check if I can update it to 9.2.2 for more wider range of python version.

* Good point! I will refine the description.

Thank you very much again for your kind suggestions.

**Comment by Ricky-Tigg** [comment]
Happy to contribute, somehow poorly.
- I could test on Rocky 9.1; it has led to a new report. 
- It appears that _requirements.txt_ may not require any modification since without any, `python3.11 -m venv venv` run successfully.
- I was to suggest `tree -dL 1` to illustrate the location of _solvers_. Late  i am, as you did it fine.

Suggestion : in order to obtain the compressed file containing the **solver executables**, the instruction could deserve a command involving either `curl` or `wget`.

**Comment by jiban** [comment]
Yes. I added the commands for Linux users just now.
https://nextfoam.github.io/baram-pages/docs/installation/#linux

**Comment by Ricky-Tigg** [comment]
It can hardly be better documented.

**Comment by jaxiballi** [comment]
compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tables
Failed to build tables
ERROR: Could not build wheels for tables, which is required to install pyproject.toml-based projects
please help unable to install baram on ubuntu 24 lts

**Comment by jiban** [comment]
Hi, @jaxiballi.
Which python version are you working with?
Please note that BARAM is working on **python 3.9.x**.
