### ISSUE TITLE
Wayland session | Rolling menus can be detached

### ISSUE THREAD

**Issue by Ricky-Tigg** [nextfoam/baram#23]
**kernel v.:** 6.0 | **distribution:** Fedora | **baram v.**: 22.0.4 | **window system:** Wayland (served by Mutter in my user session)

Hello. Running BARAM:
```
[(...)]$ python3.11 -m venv venv && source ./venv/bin/activate
(venv) [(...)]$ python main.py
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```
Rolling menus can be detached from their window. **Not reproducible on X.org**. Illustration:

![baram_v _22 0 4_Wayland](https://user-images.githubusercontent.com/26058215/204801553-55da0e87-5273-4cce-a2db-770a327929e9.png)

**Comment by jiban** [comment]
Thank you for the clarification.
Yes, I saw it on Windows too.
I could not find the root cause of it.
Actually that rolling menu is managed by QT itself, and I have no control of it.
However, I will investigate it more.

**Comment by jiban** [comment]
In replying to Issue #26, a question has arisen.
According to my test and your error in Issue #26, MainWindow(The window you captured above) cannot be opened on _wayland_.
How could you see the captured screen on _wayland_?
(There might be a difference between your installation of Rocky Linux and mine)

**Comment by Ricky-Tigg** [comment]
_Ticket 26_ is made against a VM (QEMU Standard PC _Q35 + ICH9, 2009_),. and **Rocky** with defaults, among them **Gnome 40.4.0**.

Here the machine is physical, **Gnome 43.1**, and **Fedora**. Regardless a session being on X.org or Wayland, by pressing the key dedicated for screen printing e.g. <kbd>prt scr</kbd> on my laptop, a capture can be taken. You shall see by testing.

**Comment by Ricky-Tigg** [comment]
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version}' gcc python3 vte291 glibc openmpi git-core xcb-util* qt*
gcc 12.2.1
git-core 2.38.1
glibc 2.36
openmpi 4.1.4
python3 3.11.0
qt 4.8.7
qt-common 4.8.7
qt-settings 37.0
qt-x11 4.8.7
qt5-qtbase 5.15.7
qt5-qtbase-common 5.15.7
qt5-qtbase-gui 5.15.7
qt5-qtcharts 5.15.7
qt5-qtdeclarative 5.15.7
qt5-qtwayland 5.15.7
qt5-qtx11extras 5.15.7
qt5-qtxmlpatterns 5.15.7
qt5-srpm-macros 5.15.7
qt6-qtbase 6.4.1
qt6-qtbase-common 6.4.1
qt6-qtbase-gui 6.4.1
qt6-qtdeclarative 6.4.1
qt6-qtsvg 6.4.1
qt6-qtwayland 6.4.1
vte291 0.70.1
xcb-util 0.4.0
xcb-util-image 0.4.0
xcb-util-keysyms 0.4.0
xcb-util-renderutil 0.3.9
xcb-util-wm 0.4.1
```

**Comment by Ricky-Tigg** [comment]
```
]$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version}' gcc python3 vte291 glibc openmpi git-core xcb-util* qt* | column
gcc 12.2.1			qt5-qtx11extras 5.15.7
git-core 2.38.1			qt5-qtxmlpatterns 5.15.7
glibc 2.36			qt5-srpm-macros 5.15.7
openmpi 4.1.4			qt6-qtbase 6.4.1
python3 3.11.0			qt6-qtbase-common 6.4.1
qt 4.8.7			qt6-qtbase-gui 6.4.1
qt-common 4.8.7			qt6-qtdeclarative 6.4.1
qt-settings 37.0		qt6-qtsvg 6.4.1
qt-x11 4.8.7			qt6-qtwayland 6.4.1
qt5-qtbase 5.15.7		vte291 0.70.1
qt5-qtbase-common 5.15.7	xcb-util 0.4.0
qt5-qtbase-gui 5.15.7		xcb-util-image 0.4.0
qt5-qtcharts 5.15.7		xcb-util-keysyms 0.4.0
qt5-qtdeclarative 5.15.7	xcb-util-renderutil 0.3.9
qt5-qtwayland 5.15.7		xcb-util-wm 0.4.1

```

**Comment by jiban** [comment]
Ok, Now I see you have so many different testing environments!

By the way, I found that even QT designer showed the detaching.
It might be an internal bug of QT itself.

![image](https://user-images.githubusercontent.com/1674177/205783282-941e6b6e-3c1d-4abc-92a3-14dde156d870.png)

**Comment by Ricky-Tigg** [comment]
Indeed, that what it seems to me as well, then we can close.
