### ISSUE TITLE
QT error while running on Ubuntu 20.04

### ISSUE THREAD

**Issue by sunilvbharadwaj** [nextfoam/baram#25]
I am getting an error like this:

`` "QSocketNotifier: Can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with `QThread" ``

when I run main.py file. 

Anyone else running into this issue?

**Comment by jiban** [comment]
Hello, sunilvbharadwaj.
I tried running BARAM on Ubuntu 20.04 but could not reproduce the problem.
Following is my system information.
```
jake@vmlinux:~/workspace/baram$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
jake@vmlinux:~/workspace/baram$
```
Could you send me the whole console output starting from activating python virtual environment like following?
```
jake@vmlinux:~/workspace/baram$ source venv/bin/activate
(venv) jake@vmlinux:~/workspace/baram$ python main.py
```
BARAM Running...
```
(venv) jake@vmlinux:~/workspace/baram$ deactivate
jake@vmlinux:~/workspace/baram$
```

**Comment by sunilvbharadwaj** [comment]
`(base)` abb@server2:~$ conda deactivate
abb@server2:~$ cd Software/baram
abb@server2:~/Software/baram$ source ~/venv/bin/activate
(venv) abb@server2:~/Software/baram$ python main.py
QSocketNotifier: Can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread ``

Is this what you are looking for? And thanks for replying.

**Comment by jiban** [comment]
Yes, But it seems that there was no back trace message from python.
Did BARAM go running after the message or it showed more messages and stopped?

**Comment by sunilvbharadwaj** [comment]
Hi Jiban, 

It just showed me this message. Didn't open the application.

**Comment by jiban** [comment]
The message makes me suspect that _qasync_ python module is not working well.
_qasync_ module provides asynchronous function based on QT Threads.
Could you give me the package list for me to see if virtual environment is setup correctly?
You can get the list with `pip list` command in python virtual environment.
```
(venv) C:\Users\jakej\Documents\workspace\baram>pip list
Package            Version
------------------ -------
aiohttp            3.8.1  
aiosignal          1.2.0  
async-timeout      4.0.2  
attrs              21.4.0 
charset-normalizer 2.1.0  
cycler             0.11.0 
elementpath        2.5.1  
filelock           3.7.1  
fonttools          4.34.4 
frozenlist         1.3.0  
h5py               3.6.0  
idna               3.3
kiwisolver         1.4.4
lxml               4.9.1
matplotlib         3.5.2
multidict          6.0.2
numexpr            2.8.3
numpy              1.23.5
packaging          21.3
pandas             1.4.2
Pillow             9.3.0
pip                21.3.1
psutil             5.9.1
pyparsing          3.0.9
PySide6            6.2.4
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
qasync             0.23.0
screeninfo         0.8
setuptools         60.2.0
shiboken6          6.2.4
six                1.16.0
tables             3.7.0
vtk                9.2.2
wheel              0.37.1
wslink             1.8.2
xmlschema          1.10.0
yarl               1.7.2
WARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Users\jakej\Documents\workspace\baram\venv\Scripts\python.exe -m pip install --upgrade pip' command.

(venv) C:\Users\jakej\Documents\workspace\baram>
```

**Comment by sunilvbharadwaj** [comment]
Hi Jiban, I upgraded the pip too. 

Let me try with a different installation of Ubuntu or Rocky linux. Then I can rule out this being a Baram error. 
I will keep this ticket open till then. Thanks.

**Comment by jiban** [comment]
Sure, I will be waiting. Thank you.

**Comment by sunilvbharadwaj** [comment]
`aiohttp            3.8.1
aiosignal          1.2.0
async-timeout      4.0.2
attrs              21.4.0
charset-normalizer 2.1.0
cycler             0.11.0
elementpath        2.5.1
filelock           3.7.1
fonttools          4.34.4
frozenlist         1.3.0
h5py               3.6.0
idna               3.3
kiwisolver         1.4.4
lxml               4.8.0
matplotlib         3.5.2
multidict          6.0.2
numexpr            2.8.3
numpy              1.19.5
packaging          21.3
pandas             1.4.2
Pillow             9.2.0
pip                22.3.1
psutil             5.9.1
pyparsing          3.0.9
PyQt5              5.15.7
PyQt5-Qt5          5.15.2
PyQt5-sip          12.11.0
PySide2            5.15.2.1
PySide6            6.2.4
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
qasync             0.23.0
screeninfo         0.8
setuptools         58.1.0
shiboken2          5.15.2.1
shiboken6          6.2.4
six                1.16.0
tables             3.7.0
vtk                9.1.0
wslink             1.9.1
xmlschema          1.10.0
yarl               1.7.2
`

**Comment by jiban** [comment]
Dear sunilvbharadwaj,
I could see PyQt and PySide2 as well as PySide6 in your list.
It's different from the virtual environment where BARAM is supposed to run in.
Only the packages in _requirements.txt_ and their dependency are expected in the _venv_(virtual environment for BARAM).
Could you try it in clean environment?

**Comment by jiban** [comment]
Closed because no response for a long time
