### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by hetanshu9** [nextfoam/baram#29]
At the time of startup of Baram on MacBook Air M1 it throws error.
On entering "python main.py" it shows error as in attached screenshot.
![Image 28-12-22 at 11 26 PM](https://user-images.githubusercontent.com/97584116/209853263-0b4596f8-d2bf-4823-89ba-82948808f47d.jpg)

Thanks

**Comment by jiban** [comment]
Oh. Could you change the line 53 of `/Users/hetanshu/baram/openfoam/run.py` file like following?
```Python
ompiPath = glob.glob(str(OPENFOAM / 'lib' / 'sys-openmpi*'))[0]  # No Validity Check. It should exist.
```
It's just to put `sys-` in front of `openmpi*`.

**Comment by hetanshu9** [comment]
Thanks for prompt response, after making suggested correction it again throws error as per attached screenshot.
![Image 29-12-22 at 8 01 AM](https://user-images.githubusercontent.com/97584116/209895876-5ee2ee63-06ea-449e-ad2d-504b9fc9bceb.jpg)

**Comment by jiban** [comment]
You can just delete line 54 and line 58 in `/Users/hetanshu/baram/openfoam/run.py`

![image](https://user-images.githubusercontent.com/1674177/209898273-3517b8f1-0a9d-43fa-bb37-d704591c1b7c.png)

Be the way, I found that your mac has M1 that is not supported by BARAM solvers yet.
Current solvers for macOS are compiled for Intel CPU only.
Solvers for M1 will be available next month. ( And above errors will be fixed too)
I will let you know as soon as they get available.

**Comment by hetanshu9** [comment]
ok thanks

**Comment by jiban** [comment]
Hi, @hetanshu9.
Installation package for macOS with Apple silicon has released today.
You may want to try it.
For more information, refer to [BARAM Page](https://baramcfd.org/).
