### ISSUE TITLE
Translated string with no effect in Baram

### ISSUE THREAD

**Issue by Ricky-Tigg** [nextfoam/baram#31]
**Baram v.:** 22.1.0 | The version can't be determined in GUI. It would be worth an option in GUI, e.g. _About_, aimed to inform at least the version of Baram, and ideally with the version of the underlying software, which i conceive is Qt.

Hello. In Qt Linguist using Qt v. 6.2.4, translated string "_Error occurred_:\n" belonging to context _ProcessInformationPage_ has no effect in Baram though the conversion appeared to be processed successfully for the related code section; output truncated:
```
(venv) [(...)]$ python convertUi.py
  [78/83] Converting... process_information_page.ui -> process_information_page_ui.py
```

**Comment by jiban** [comment]
Yes, I agree with you. About page is definitely necessary at least for version. I will prepare it.

I could reproduce the translation issue and looking into it.

**Comment by Ricky-Tigg** [comment]
I had left unmentioned –intentionally– the implicit mentions coming along with the version, which are the _license_ and _copyright_. That may not have been obvious to you. Also if needed, here is a relevant sample illustrating a possible suitable representation.

![model](https://user-images.githubusercontent.com/26058215/212924101-92d179cc-2599-4166-b21a-206b111e87c1.png)

**Comment by jiban** [comment]
Sure, I will include _license_ and _copyright_ too. Thank you.

**Comment by jiban** [comment]
By the way, I failed to keep reproducing the translation issue.
Could you send me `resources/locale/baram_fi.ts` file that you tried with?

**Comment by Ricky-Tigg** [comment]
[baram_fi.txt](https://github.com/nextfoam/baram/files/10444799/baram_fi.txt) ;as usual, extensions non-supported by GitHub changed to txt.

**Comment by jiban** [comment]
I've tested the translation with your file, and it seems to work correctly.
(Unfortunately, I could not figure out why I could not reproduce it. Maybe the other work that was done for dynamic application of locale change could affect the behavior)
I will include your translation file in the upcoming release so that you can confirm it's working.
