### ISSUE TITLE
Not working on Mac - maybe due to issue in the Solvers file for Mac

### ISSUE THREAD

**Issue by monugeni** [nextfoam/baram#32]
**Describe the bug**

I am following the installation instructions as per the INSTALL.md file.

When I try to start Baram using:

python main.py

I get the following error:

```
  File "/Users/tan/baram-mac/baram/main.py", line 24, in <module>
    from view.main_window.start_window import Baram
  File "/Users/tan/baram-mac/baram/view/main_window/start_window.py", line 19, in <module>
    from coredb.project import Project, ProjectOpenType
  File "/Users/tan/baram-mac/baram/coredb/project.py", line 13, in <module>
    import openfoam.run as run
  File "/Users/tan/baram-mac/baram/openfoam/run.py", line 53, in <module>
    ompiPath = glob.glob(str(OPENFOAM / 'lib' / 'openmpi*'))[0]  # No Validity Check. It should exist.
IndexError: list index out of range
```

**To Reproduce**
1. Follow installation instructions as per INSTALL.md
2. Use the Mac solvers file from : [](http://d3c6e16xufx1gb.cloudfront.net/solvers_mac_20220908.tar.gz)
3. python main.py

**Expected behavior**
Baram should start. 
It is working fine on Linux.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Python: 3.9
 
**Additional context**
I believe the problem is in the Solvers file. There are no files in the lib directory with names matching openmpi*
The Solvers file for linux has a number of such files existing in the lib folder.
Please check.

**Comment by niuniuaba** [comment]
I am using centos linux and I can reproduce the same problem. And the fix above doesn't work because openmpi* is in lib and sys-openmpi* is in tlib. So what I need to do is to modify only line 54 in run.py by changing openmpi* to sys-openmpi*.

Hope this helps.

**Comment by monugeni** [comment]
Thanks for your message.
The latest Baram works fine without any changes. It works on Apple Silicon
mac also and I hope shall work ok on Centos also.

**Comment by jiban** [comment]
Dear @monugeni,
I'm happy to hear that.
Thank you for sharing the information.
Please don't hesitate to let me know if you have any other trouble or suggestion.
