### ISSUE TITLE
Unable to import Mesh with Baram on Mac

### ISSUE THREAD

**Issue by monugeni** [nextfoam/baram#33]
When I try to import a mesh ( I tried both Gmsh and UNV mesh), I get the following error:

```
dyld[14675]: Library not loaded: /Users/jhgill/Applications/OpenFOAM/NextFOAM-v2206/platforms/darwin64ClangDPInt32Opt/lib/libmeshTools.dylib
  Referenced from: <4602445A-AE1C-3728-B428-2286BA5BE0D4> /Users/tan/baram-mac/baram/solvers/openfoam/bin/ideasUnvToFoam
  Reason: tried: '/Users/jhgill/Applications/OpenFOAM/NextFOAM-v2206/platforms/darwin64ClangDPInt32Opt/lib/libmeshTools.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jhgill/Applications/OpenFOAM/NextFOAM-v2206/platforms/darwin64ClangDPInt32Opt/lib/libmeshTools.dylib' (no such file), '/Users/jhgill/Applications/OpenFOAM/NextFOAM-v2206/platforms/darwin64ClangDPInt32Opt/lib/libmeshTools.dylib' (no such file), '/usr/local/lib/libmeshTools.dylib' (no such file), '/usr/lib/libmeshTools.dylib' (no such file, not in dyld cache)

```

It is trying to find some file in /Users/jhgill !
Please check.

Is there something else I need to install to get this to work?

**Comment by jiban** [comment]
I'm afraid your path might not be configured.
Could you please check if you have this file in your mac?
```/Users/tan/baram-mac/baram/solvers/openfoam/lib/libmeshTools.dylib```

If so, please send me your modified file of ```/Users/tan/baram-mac/baram/openfoam/run.py```.
we need to confirm if it has the path definition.
Thank you.

**Comment by jiban** [comment]
Unfortunately macOS with Intel silicon is no longer supported.
However, macOS with Apple silicon has been supported since v23.1.0.

Jake
