### ISSUE TITLE
Import STL in BARAM.

### ISSUE THREAD

**Issue by Rafonwski** [nextfoam/baram#34]
Hi, I'm a student trying to use BARAM for my thesis. Is there a guide to use BARAM? And is it possible to open on STL file made with, such as, AutoCAD with BARAM?

**Comment by jiban** [comment]
Hi, Rafonwski.
_BARAM_ is able to import several types of _mesh files_ as OpenFOAM pre-processors support.
However, _STL_ is a file format for geometry, which can be a base for generating a mesh file.
You can use [_snappyHexMesh_](https://www.openfoam.com/documentation/user-guide/4-mesh-generation-and-conversion/4.4-mesh-generation-with-the-snappyhexmesh-utility) or [_SALOME_](http://www.salome-platform.org/) to generate mesh from the _STL_.
By the way, a GUI for _snappyHexMesh_, which is an OpenFOAM pre-processor utility, is under development and will be released this year.

**Comment by WHUT666** [comment]
> Hi, Rafonwski. _BARAM_ is able to import several types of _mesh files_ as OpenFOAM pre-processors support. However, _STL_ is a file format for geometry, which can be a base for generating a mesh file. You can use [_snappyHexMesh_](https://www.openfoam.com/documentation/user-guide/4-mesh-generation-and-conversion/4.4-mesh-generation-with-the-snappyhexmesh-utility) or [_SALOME_](http://www.salome-platform.org/) to generate mesh from the _STL_. By the way, a GUI for _snappyHexMesh_, which is an OpenFOAM pre-processor utility, is under development and will be released this year.

The BARAM Snappy Guides have been updated. When will the mesh feature be released？

**Comment by jiban** [comment]
I'm still working on it and hope it will be available before 19th of this month.

**Comment by WHUT666** [comment]
> I'm still working on it and hope it will be available before 19th of this month.

This is great. I'm looking forward to it
