### ISSUE TITLE
Proposal: solvers folder with version control

### ISSUE THREAD

**Issue by kjrstory** [nextfoam/baram#36]
Why the executable files in the "solvers" folder are not publicly version control? I suggest version controlling those files as well. If you want to version control them in a separate GitHub repository and provide them as compressed files instead of source code, it would be beneficial to utilize Git LFS (Large File Storage) for version controlling large files. If you utilize the Git Submodule feature, it is possible to establish connections between repositories. If all of this can be accomplished, it might be feasible to create a single script for the installation process. If you truly need assistance with these tasks, I can provide help.

**Comment by jiban** [comment]
Thank you for the advice.
Unfortunately, solver source code version control is not ready for open yet.
We are transferring our legacy code to the new code base and it would take some time to complete.
In the meantime, if you are interested in the solver, you can download current source code from following link.

https://d3c6e16xufx1gb.cloudfront.net/OpenFOAM-N/OpenFOAM-N1.2.xz

**Comment by kjrstory** [comment]
Thank you for your information. In that case, I think I can wait until the source code is open without a separate repository. It would be good to close this issue when the solver code is opened.

**Comment by jiban** [comment]
Dear @kjrstory 
You can find the source code of solver, which is used in BARAM.
https://github.com/nextfoam/nextfoam-cfd
