### ISSUE TITLE
Download of executable not possible

### ISSUE THREAD

**Issue by flowgeek** [nextfoam/baram#39]
the download link for the windows version on this site does not work: 

https://nextfoam.github.io/baram-pages/docs/installation/

clicking the link leads to an "access denied" message:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BNWASE7K6Z30A9NT</RequestId>
<HostId>1Aa8CohXVySaEHQ+jghsNRXLHxqrxLc5NunkesRowLHwL4xDOkNlusOLX0Nq8zy5llFU5RX/Q/k=</HostId>
</Error>

**Comment by jiban** [comment]
Oh, Thank you very much for letting me know about it.
It's fixed now. I'm sorry for the inconvenience.
Have a nice day!

**Comment by flowgeek** [comment]
thanks! works now

and great work!

cheers
alex
