### ISSUE TITLE
Tooltips for Graphic Toolbar Icons

### ISSUE THREAD

**Issue by kjrstory** [nextfoam/baram#44]
**Is your feature request related to a problem? Please describe.**
I'd like tooltips for the icons in the graphic toolbar. Currently, there are only icons, and it's confusing as to what each function does.

**Describe the solution you'd like**
Whether to make changes in the UI file or add them to the .py file, but it seems better to add them to the UI file.

**Describe alternatives you've considered**

**Additional context**
You can assign this task to me.
It would be a good idea to have tooltips for other buttons as well, but since the other buttons have strings, let's start by adding tooltips to the graphic toolbar buttons that only have icons.

**Comment by jiban** [comment]
Yes, I agree that tooltips help users understand what those icons do if the icons are graphics-only icons.
And thank you for your suggestion.
