### ISSUE TITLE
Parallel Solver is not work in EndeavourOS

### ISSUE THREAD

**Issue by dhkima-higenmotor** [nextfoam/baram#54]
**Describe the bug**

* Arch Linux 기반의 EndaevourOS에서, baramFlow Solver를 Parallel Run을 시도할 때 Segmentation error가 발생합니다.
* 하지만 Single core run은 잘 작동합니다.
* 추측되는 이유는, Arch AUR에서 발견할 수 있는 `parmetis` 패키지의 Build가 실패하기 때문에, 대신 `parmetis-git` 패키지로 대체하여 가장 최신 버전을 설치하였는데, 이 때문에 현재의 baramFlow Solver와 호환성 문제가 있는 것으로 보입니다.
* EndeavourOS가 아닌 기본형 Arch Linux의 경우에는, `parmetis` 패키지가 잘 설치되고, baramFlow Solver의 Parallel Running이 잘 작동합니다.

* In EndaevourOS based on Arch Linux, a Segmentation error occurs when attempting to parallel run the baramFlow Solver.
* But Single core run works fine.
* The presumed reason is that the build of the `parmetis` package found in Arch AUR failed, so the most recent version was installed instead, replacing it with the `parmetis-git` package, which caused a compatibility issue with the current baramFlow Solver. It appears that there is.
* In the case of basic Arch Linux, not EndeavorOS, the `parmetis` package is installed well, and Parallel Running of baramFlow Solver works well.

**To Reproduce**
1. EndeavourOS
2. `parmetis-git` is installed from AUR
3. Try baramFlow with parallel solving
4. Solver fail and Segemntation error

**Expected behavior**
* I hope Solver will be updated to be compatible with the latest version of parmetis.
* 최신 버전의 parmetis와 호환될 수 있도록 Solver 업데이트가 잘 이루어지기를 기대합니다.

**Screenshots**
![Screenshot_2024-01-16_10-01-02](https://github.com/nextfoam/baram/assets/131317293/d158cba6-0b65-4b67-a85a-05f850e1486f)
![Screenshot_2024-01-16_10-01-39](https://github.com/nextfoam/baram/assets/131317293/663a6ff9-94d1-46d4-9e88-064d7ad26534)

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Browser : Firefox
 - Version of parmetis : parmetis-git-r45.8ee6a37-1-x86_64
 - PKGBUILD of parmetis-git

```
# Maintainer: Carlos Aznarán <caznaranl@uni.pe>
_base=ParMETIS
pkgname=${_base,,}-git
pkgver=r45.8ee6a37
pkgrel=1
arch=(x86_64)
pkgdesc="Parallel Graph Partitioning and Fill-reducing Matrix Ordering (git version)"
url="https://github.com/KarypisLab/${_base}"
license=('custom')
depends=(metis openmpi)
makedepends=(cmake git)
options=(docs)
source=(git+${url}.git#branch=main)
sha512sums=('SKIP')
provides=(${_base,,})
conflicts=(${_base,,})

pkgver() {
  cd ${_base}
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short=7 HEAD)"
}

build() {
  cd ${_base}
  make config \
    shared=1 \
    cc=mpicc \
    prefix=/usr \
    gklib_path=/usr \
    metis_path=/usr
}

package() {
  cd ${_base}
  make install DESTDIR="${pkgdir}"
  install -Dm 644 LICENSE -t "${pkgdir}/usr/share/licenses/${pkgname}"
}
```

### Comment
* 좋은 소프트웨어를 공개해 주셔서 대단히 감사합니다.
* 본 이슈는 공식지원대상에 포함되어 있지 않은 EndeavourOS 관련된 것이므로, 중요치 않을 수도 있을 것 같지만 정보공유 차원에서 올려 보았습니다.

**Comment by kdg5424** [comment]
안녕하세요 김동호님. BARAM에 관심을 가져주셔서 정말 감사합니다.
혹시 BARAM 설치 및 실행은 Apptatiner로 하신건지 아니면 다른 방법을 사용하신건지 알 수 있을까요?

**Comment by dhkima-higenmotor** [comment]
* Ref : https://baramcfd.org/docs/installation/
* 설치 및 실행은 Apptatiner 등의 컨테이너가 아니고, Installing BARAM from Source Code 방법 안내에 따라 실시하였습니다.
* Apptainer 방법은 따로 시도해 보고 여기에 다시 보고드릴께요.

**Comment by kdg5424** [comment]
알겠습니다. BARAM에 관심 가져주셔서 정말 감사합니다.
BARAM과 관련된 문의 사항 있으신 경우 아래 메일 주소로 연락 주시면 되겠습니다.

메일 주소 : dkkim@nextfoam.co.kr

**Comment by dhkima-higenmotor** [comment]
### Apptainer
* 안내해 주신대로, Apptainer로 설치후 이상없이 Parallel Run에 성공하였습니다!  감사합니다.
* Container 설치시 성능저하가 약간 있으니 피하라는 주변의 조언 때문에 선입견이 있었는데, 막상 해 보니 성능저하가 체감되는 부분을 느끼지 못하겠습니다.
* 사소한 단점은, Simbolic Linked Directory 인식이 안되는 것 같습니다. (Apptainer의 특성으로 보입니다)
![Screenshot_2024-01-17_12-47-11](https://github.com/nextfoam/baram/assets/131317293/01df5c6d-ae53-4111-8cc0-fd3d9dd5e2fc)
![Screenshot_2024-01-17_12-53-24](https://github.com/nextfoam/baram/assets/131317293/9f875887-4705-43cb-a919-7cb288b2ac66)

**Comment by kdg5424** [comment]
Container 사용 시, 성능이 저하될 수 있다는 얘기는 저희도 알고 있었습니다.
하지만 저희 내부적으로 테스트 시, 체감으로 느껴질 정도 성능 저하는 없었습니다.
아마 SW와 HW가 발전하면서 그렇게 되지 않았을까 생각이 드네요.

다시 한번 BARAM에 관심을 가져주셔서 정말 감사합니다.

www.nextfoam.co.kr

위 사이트에 방문하시면 BARAM과 OpenFOAM에 관련한 자료 및 교육 내용을 조금 더 자세하게 확인하실 수 있습니다.
나중에 기회가 되신다면 홈페이지 방문 부탁드리겠습니다.

BARAM 사용하다 문제가 되는 사항은 언제든지 아래 메일 주소로 문의 남겨주시면 감사하겠습니다.

marketing@nextfoam.co.kr
dkkim@nextfoam.co.kr

**Comment by dhkima-higenmotor** [comment]
네! 잘 알겠습니다.
저희 회사에서는 아직 CFD를 사용한 사례가 없었는데(국책과제로 외부에서 해오는 경우 제외), 
처음 시도해 보고 있는 중이라서, BARAM을 통해서 조금 더 쉽게 접근해 볼 수 있는 것 같습니다.
몇 달 정도에 걸쳐서 자체 스터디, 관심있는 동료들을 모으고 있는 중이라서
어느정도 기반이 된다 싶으면 Nextfoam과 실질적인 인연이 될 수도 있을 것으로 기대하고 있습니다.
교육 서비스도 그렇고, 자사 특화 솔루션 같은 것도 귀사에 의뢰드려 만들어볼 기회도 있지 않을까 싶기도 합니다.
오랫동안 꾸준하게 서비스를 유지해 주시고 계신 것으로 알고 있는데 그래서 더욱 신뢰가 갑니다.
항상 건승하시기를 바랍니다.

**Comment by kdg5424** [comment]
알겠습니다.^^ 필요하실 때 언제든지 연락주시면 감사하겠습니다.
