### ISSUE TITLE
X Error of failed request:  BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by shiyezia** [nextfoam/baram#55]
**Describe the bug**
When I open the CaseWizard and then create a new case， I cannot go to the main page. An error occurred：

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x9
  Serial number of failed request:  7
  Current serial number in output stream:  8

**Screenshots**
![image](https://github.com/nextfoam/baram/assets/50040543/c0b97078-30dd-4c19-abd8-d553f964e1bd)

**Desktop (please complete the following information):**
 ubuntu22.04

**Comment by jiban** [comment]
Hello, @shiyezia.
It seems like the same issue to issue #26.
Could you try the solution in issue #26?

**Comment by shiyezia** [comment]
Yes, issue has been solved.
Thank you ！
