### ISSUE TITLE
Unable to run setup.exe due to Microsoft Defender SmartScreen

### ISSUE THREAD

**Issue by jbruck** [nextfoam/baram#56]
**Describe the bug**
Microsoft Defender SmartScreen prevents the BARAM-v24.0.1-setup.exe from running as it is an unrecognised app. Publisher is listed as Unknown.

**To Reproduce**
Using Win11
Download latest release of BARAM v24.0.1-setup.exe
Attempt to run executable.

**Comment by kdg5424** [comment]
Hi @jbruck I'm Donggyu.
Is this picture right what you mean?

![image](https://github.com/nextfoam/baram/assets/133930861/76a00d0c-c8df-442f-b0bc-c784549d875e)

Our program is not a virus or something else. It does not damage your PC.
Click '**Run anyway**' button then, it will run installation.

Thank you for your attention on BARAM.

**Comment by jiban** [comment]
@jbruck
By the way, the binary(Setup) you downloaded was not working in parallel configuration.
New binary has replaced the old one on [baramcfd.org](https://baramcfd.org).
Please download the binary again from the site.
Sorry for the inconvenience.

**Comment by jiban** [comment]
@jbruck , Here is additional information.
You may encounter following pop-up window at first.

![image](https://github.com/nextfoam/baram/assets/1674177/c13e4ddb-1552-43eb-bb39-0b6283285e09)

If you click "More Info" in the capture, it will change like following and you can now click "Run anyway".

![image](https://github.com/nextfoam/baram/assets/1674177/abca9ae9-d8b8-41fe-8c63-69784572dcae)

**Comment by jbruck** [comment]
Thanks for your help. I was evaluating this on my work laptop, so the "run anyway" was not available. I managed to get it to run by going to the file properties and checking an "Unblock" box on the General Tab under Security.

**Comment by jiban** [comment]
Oh, I didn't think of work laptop, where apps from unknown publishers could not be installed.
Thank you for the update.
I will prepare app signing for next releases.
