### ISSUE TITLE
[SOLVED] BARAM port 8678 connection host failed (issues or bug)

### ISSUE THREAD

**Issue by lucianoambrosini** [nextfoam/baram#65]
Hello everyone,
 I am facing the error above in both applications BaramFlow and BaramMesh. Any suggestions?
 Thanks in advance.

**Comment by jiban** [comment]
Dear @lucianoambrosini, 
BARAM does not use any network port.
Could you capture the error message and let me know your running environment in detail?

-- Jake

**Comment by lucianoambrosini** [comment]
Castellation refinement Failed. [4294967295] (windows message)
Error while connecting to host, Unable to establish connection. Persistent rejection of the target computer. (10061)
Connect on sock (host=Asus, port=8678) failed, exhausted all end points
Unable to connect to 'Asus:8678',
sock error: Error = -1

This above is the error message displayed 8even in BaramFlow) I downloaded Baram 24.0.1.

**Comment by jiban** [comment]
Dear @lucianoambrosini,
I still have no clue for the issue and have a few questions to clarify it.
1. On what platform are you running Baram? (ex. Window, macOS, Linux, or WSL on Windows, ...)
2. How did you install Baram? ( ex. by windows installer or git clone, ... )
3. How do you run Baram? ( ex. by typing python command on command line, or by double-clicking on Windows, ...)
4. Are you running Baram in Cluster configuration?  
    ![image](https://github.com/nextfoam/baram/assets/1674177/45236ab9-0935-434b-8815-dbd671fc861c)

**Comment by lucianoambrosini** [comment]
You are right sorry, so:
1) Windows 10, 
2) I run the Windows installer app;
3) I run this app on Windows:
![image](https://github.com/nextfoam/baram/assets/16278183/e138625a-6159-4b75-81fb-df7b73be0e41)
4) I run it on the local machine
![image](https://github.com/nextfoam/baram/assets/16278183/a257022c-6c47-41c9-ab00-81f804e95d61)

I am trying to use BARAM to run some Buildings CFD analysis.

Thank you in advance for your help.

**Comment by jiban** [comment]
I'm strongly suspecting that the problem comes from MPI.
Could you check your MPI installation status in Windows Settings?
![image](https://github.com/nextfoam/baram/assets/1674177/1efab873-1b2d-4c16-a03d-a327049353f3)

**Comment by lucianoambrosini** [comment]
Thanks for your prompt response!
![image](https://github.com/nextfoam/baram/assets/16278183/92b45a3a-fa45-4404-9124-2abd191ac5ef)

so I noticed that the MPI SDK is missing.

**Comment by jiban** [comment]
I found a similar issue [here](https://www3.aps.anl.gov/forums/elegant/viewtopic.php?t=678).
> Error while connecting to host, No connection could be made because the target machine actively refused it. (10061)
Connect on sock (host=*computer name*, port=8676) failed, exhaused all end points
Unable to connect to '*computer name*:8676',
sock error: Error = -1

Do you have any other MPI installed on your Windows?
Could you check if the path for MS-MPI is the first one?
```cmd
Microsoft Windows [Version 10.0.19045.4170]
(c) Microsoft Corporation. All rights reserved.

C:\Users\jakej>where mpiexec
C:\Program Files\Microsoft MPI\Bin\mpiexec.exe

C:\Users\jakej>
```

**Comment by lucianoambrosini** [comment]
Thankd for your feedback, I checked it and I found out this:

C:\Users\lucia>where mpiexec
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt\mpiexec.exe
C:\Program Files\Microsoft MPI\Bin\mpiexec.exe

C:\Users\lucia>

**Comment by jiban** [comment]
Yes, you definitely have Intel MPI installed on your Windows.
Could you try uninstalling it from "*Settings > Apps*" and restarting your computer, then running BARAM?

**Comment by lucianoambrosini** [comment]
Perfect!
Thank you! I have renamed the intel MPI file and now BaramMesh and Flow go ahead in their calculation. Now I must find some tutorials to use them specifically for buildings/AEC industry. Any advice is well accepted :)
Thank you for your support.

**Comment by kdg5424** [comment]
Hi @lucianoambrosini . This is donggyu. I want to know the more detail information of you.
You mentioned you need some tutorials for buildings/AEC. There are some fields in building/AEC like HVAC, plant engineering, boiler, etc.
So I want to know which field exactly are you in.
And which tutorials do you need?
Thanks

**Comment by jiban** [comment]
Closed because no response for a long time

**Comment by lucianoambrosini** [comment]
Sorry for the tremendous delay,

AEC industry but I more focused on the Urban and indoor design simulation, especially in knowing and assessing the wind behaviour over the building facades.

**Comment by kdg5424** [comment]
Hello @lucianoambrosini. This is Donggyu.

I'm really sorry but currently there isn't a specific example of building wind pressure tutorials that suits your needs perfectly.
However, there are similar examples sucs as airfoil, automobile and cantilever beams external aerodynamics tutorials.
Since there is demand for building wind pressure examples, we plan to create on soon.

And which CFD SW do you use now? ANSYS, CCM or anything else?
I'm just asking out of curiosity.

Best regards

Donggyu kim

**Comment by lucianoambrosini** [comment]
Thank you for your prompt response.

Generally I used to work with some specific Grasshopper plugins (that deploy OpenFoam as CFD engine), or sometimes with ANSYS.
Thank you for your advice about "similar examples".

Best regards,

**Comment by kdg5424** [comment]
Oh could you let us know Grasshopper plugin? I've never heard about that.
Is it the specific solver for building wind pressure or general solver?

Best regards.

**Comment by lucianoambrosini** [comment]
Certainly. Grasshopper is a Visual Programming Language (VPL) for Rhinoceros, which is a 3D modeling NURBS software developed by McNeel & Associates. Since its inception in 2008, Grasshopper has significantly expanded, and a plethora of plugins have been created. In the realm of environmental design, two major projects stand out: Ladybug Tools and ClimateStudio.

Regarding CFD analysis specifically:
1) Butterfly is available from Ladybug Tools;
2) Eddy3D is provided by some developers from ClimateStudio;

Both serve as Grasshopper user interfaces for managing the OpenFoam engine.

I trust this information will be helpful to you.

 Shall we begin developing a new GH plugin? 😉
 
 Best regards.

**Comment by kdg5424** [comment]
Thank you for your kind exlpain.

Could you let me know why you need that plugin and how are you going to use it?
We have the roadmap and priority for the BARAM development.
And by our judgement and decision, if the users seriously need the plugin (Grasshopper), we should decide to implement the plugin.

So could you give us more detail information?

Best regards

**Comment by lucianoambrosini** [comment]
The fundamental concept is to incorporate the capability for conducting CFD analysis within software platforms such as Rhino + Grasshopper, which excel in 3D object management. This is particularly crucial considering that most AEC projects, especially in architecture and engineering, utilize this environment for optimization processes. This is a succinct viewpoint.

Best regards,
