### ISSUE TITLE
No menu' Energy available in a fresh ubuntu 20.04 virtual machine.

### ISSUE THREAD

**Issue by andprad74** [nextfoam/baram#66]
Dear all,
in a fresh version of ubuntu 20.04 i have install baramcfd by following the site instructions.
Everything was ok but it's not possible to select the energy model as shown in the picture.
Thanks in advance for a support.
A.

![linux_baram_no_energy_model](https://github.com/nextfoam/baram/assets/131922029/10133275-e234-4216-8075-3290a4b87c68)

**Comment by kdg5424** [comment]
Hi @andprad74. This is donggyu.
In my opinion, the reason why there is no energy available is because you didn't import the mesh.
I recommend you to use energy model after you import the mesh.
Thanks.

**Comment by kdg5424** [comment]
Glad to hear that!
If you have any questions in BARAM, please don't mind to ask.
Thanks!
