### ISSUE TITLE
start with error

### ISSUE THREAD

**Issue by shiyezia** [nextfoam/baram#67]
start with error

**Screenshots**
![image](https://github.com/nextfoam/baram/assets/50040543/dd6e25e2-4a8a-4fce-bf36-577e102f4a82)

Ubuntu22.4 

How can i deal with it?

**Comment by jiban** [comment]
Hi, @shiyezia.
Could you tell me what you did before it happened?
I'd like to know the situation that made this error.

By the way, your code is too old, and you'd better to update it or to download new code.

Thank you.

**Comment by jiban** [comment]
Closed because no response for a long time
