### ISSUE TITLE
force monitor: reference pressure issue

### ISSUE THREAD

**Issue by kjrstory** [nextfoam/baram#70]
문서페이지의 튜토리얼 중 2번째 문제(https://baramcfd.org/tutorials/2023/09/05/AhmedBody-post/) 인 Ahmed Body를 하던 중에 Force 모니터가 생각한대로  출력이 되지 않습니다.
 그림을 보면 (아직 수렴이 다 되지 않았지만) Cd는 약 0.32로 실험값과 비슷한데 비해 Cl은 약 -2.5로 실험값과  부호와 크기가 큰 차이가 납니다.  
![Capture1](https://github.com/nextfoam/baram/assets/7046937/82853dca-9a58-41df-867c-cc028f1eec70) 
GUI에서 Reference Values 항목의 Operating Pressure값을 바꿔도 Cl이 동일합니다.  
모니터 Plot과 postProcessing폴더의 텍스트 파일 둘 다 확인하였습니다.
이에 대한 원인을 분석 중 pRef가 잘못 들어가는 것이 아닌가 추정됩니다.  
baram에 의해 만들어진 control dict의 force function을 살펴보면   
 ```
  patches
        (
          ...
        );
      rho rho;
      Aref 0.056;
      lRef 1;
      magUInf 40;
      rhoInf 1.2;
      dragDir
  (1 0 0);
      liftDir
  (0 1 0);
      CofR
  (0 0 0);
  ...
  ```
  이런식으로 되어있습니다.  
  여기에 pRef값이 없습니다.  
  텍스트 에디터로 강제로 아래 문구를 추가하면  (forces, forceCoeffs 둘 다)  
  ```
  patches
        (
          ...
        );
  // Reference pressure [Pa]
      pRef            101325;
      rho rho;
  ...
  ```
  다음 그림과 같이 Cl이 0.37정도로 다른 참고문헌들과 비슷해집니다.  
  
![Capture2](https://github.com/nextfoam/baram/assets/7046937/2e9bc691-49e2-4611-8415-1603884dc664)

  윈도우 v24.1.3에서 테스트 하였습니다. 리눅스에서는 값이 이상한 것만 확인하였습니다. libforce 자체가 이상한 것 같진 않고 controldict를 작성하는 부분만 잘못된 것 아닌가 생각합니다.

**Comment by kdg5424** [comment]
넥스트폼 김동규입니다.

말씀해주신 이슈는 저희가 원인을 파악하였고, 이번 BARAM v24.2.0에서 수정하여 공개하였습니다.
pRef를 operating pressure + reference value의 pressure로 작성하게 코드를 수정하였습니다.
내부 테스트 결과 Cl도 맞게 잘 나옵니다.
이 외 LES, DES, Scalar등 다양한 기능이 추가되었습니다.
BARAM v24.2.0 설치 후 테스트 해주시면 감사하겠습니다.

항상 저희 회사 프로그램인 BARAM에 관심을 가져주셔 감사합니다.

**Comment by kjrstory** [comment]
이 Commit(https://github.com/nextfoam/baram/commit/8b9ee9d9665752f53c19f45a5c1be899560b0292)과 실제 설치하고 실행하여 정상 작동함을 확인하였습니다.
빠른 조치 감사합니다.
