### ISSUE TITLE
'Generating files' never finishes after pressing 'Start Calculation'

### ISSUE THREAD

**Issue by lukaville** [nextfoam/baram#83]
**Describe the bug**
'Generating files' never finishes after pressing 'Start Calculation' (see screenshot)

**To Reproduce**
1. Create a mesh using BaramMesh e.g. using this STL file https://drive.google.com/file/d/1ULoQ5W5HzAPQ1dE7rHr84WKFKF6LwshR/view?usp=sharing and create Hex6 shape around it
3. Import to BaramFlow
4. Make one wall velocity inlet and the rest of the walls — pressure outlets, use all default parameters for the rest
5. Click 'Initialize' in initialization section
6. Click 'Start Calculation' in 'Run' section

**Expected behavior**
'Generating Files' dialog finishes or shows an error

**Desktop (please complete the following information):**
 - OS: macOS 14.3 (23D56)
 - BaramFlow version: 24.2.0

![image](https://github.com/nextfoam/baram/assets/725526/465acae7-d9e2-46b6-a972-d3ba6f1d21eb)
![image](https://github.com/nextfoam/baram/assets/725526/f9d76d7c-468a-4c9d-8eb5-c8e8b62f4782)

Attaching a case directory too:
[terrain_case.zip](https://github.com/user-attachments/files/15521975/terrain_case.zip)

**Comment by jiban** [comment]
Hi Nick,
I'm sorry for the inconvenience.
Yet I could find a clue from your case file attached here.
Thank you for that.
I will work on it and upload a new image as soon as possible.
I would take a few days.
Thank you, and have a nice day.

**Comment by jiban** [comment]
Hi Nick.
I finally could upload an updated BARAM package for macOS.
I've compiled it with the latest [Homebrew open-mpi](https://formulae.brew.sh/formula/open-mpi) package, whose version is 5.0.3 for now.
So you need to update open-mpi package on your mac if it is not the latest one.
Please feel free to let me know if you have any trouble in trying this new version.
Thank you.

--Jake

**Comment by lukaville** [comment]
I have tried the patched version, it doesn't get stuck on 'generating files' anymore. Thank you, Jake!
