### ISSUE TITLE
Installation problem of the version 24.2.0 on Ubuntu 20.04 with the both the method proposed

### ISSUE THREAD

**Issue by andprad74** [nextfoam/baram#86]
Hello
in a fresh version of Ubuntu 20.04, running inside the Virtual Box,
i try to install the last version of BaramCFD   24.2.0
As the previous versions i try to use the method "Python virtual environment".
At the end of the installation the in BarameMesh with a simple cube geometry the software was not able to perform the mesh because was not able to find the "libmpi.so.40".
After that i try with the other method  "NextFOAM build" i follow the instructions and when i run the

sudo pip3 install --ignore-installed -r requirements.txt
i received the mistake in the picture
With the version 24.0.1 everything was ok, it possible to install also the previuos version ?
Thanks in advance and
best regards.
Andrea from Italy
![baramcfd_mistake_version_24_02](https://github.com/nextfoam/baram/assets/131922029/813978a2-246f-41b4-9801-45e82ccbf812)
![baramcfd_mistake_version_24_02_biuld_nextfoam_method](https://github.com/nextfoam/baram/assets/131922029/f6851652-7651-4dfb-aca5-13f04dd0782f)

**Comment by kdg5424** [comment]
Hello @andprad74. This is Donggyu from NEXTFOAM.

Could you check these things?
- Python version
- pip version
- GCC version
- MPI version

If the problem continues, then I'll foward you a BARAM tar.gz for the linux.

Regards

Donggyu

**Comment by andprad74** [comment]
Hello Donggyu
i perform some improvement but now the problem is related to the libmpi.so.20 that is missing.
Please see the picture
Thanks in advance 
by.
Andrea
![baramcfd_libmpi20_problem](https://github.com/nextfoam/baram/assets/131922029/514e91d2-bf0a-4165-9785-f274b823e9b6)

**Comment by kdg5424** [comment]
Hello @andprad74 .
libmpi.so.20 means that you compiled with **OpenMPI version 2**.
Our solver (NextFOAM) should be compiled with OpenMPI version 4.1 or over.
So could you compile our solver with OpenMPI version 4.1 or over?

Thanks

Regards

Donggyu kim

**Comment by jiban** [comment]
Hi Andrea,
Could you try following two steps?
1. Check if *openmpi* is correctly installed.  
    You can check it with following commands.
    * `apt list openmpi*`
    * `apt list libopenmpi*`
    * `mpirun -V`
    * Output
        ```
        jake@ubuntu-jake:~/workspace$ apt list openmpi*
        Listing... Done
        openmpi-bin/focal,now 4.0.3-0ubuntu1 amd64 [installed]
        openmpi-bin/focal 4.0.3-0ubuntu1 i386
        openmpi-common/focal,focal,now 4.0.3-0ubuntu1 all [installed]
        openmpi-doc/focal,focal 4.0.3-0ubuntu1 all
        jake@ubuntu-jake:~/workspace$ apt list libopenmpi*
        Listing... Done
        libopenmpi-dev/focal,now 4.0.3-0ubuntu1 amd64 [installed]
        libopenmpi-dev/focal 4.0.3-0ubuntu1 i386
        libopenmpi3/focal,now 4.0.3-0ubuntu1 amd64 [installed,automatic]
        libopenmpi3/focal 4.0.3-0ubuntu1 i386
        jake@ubuntu-jake:~/workspace$ mpirun -V
        mpirun (Open MPI) 4.0.3

        Report bugs to http://www.open-mpi.org/community/help/
        jake@ubuntu-jake:~/workspace$
        ```
1. Unpack [this compressed file](https://d3c6e16xufx1gb.cloudfront.net/BARAM-24.2.0.tar.xz), and try running *BaramFlow* and *BaramMesh* in the folder.  
    ```
    jake@ubuntu-jake:~/workspace$ ls -l BARAM-24.2.0.tar.xz
    -rw-r--r-- 1 jake jake 247061588 Jun 11 11:02 BARAM-24.2.0.tar.xz
    jake@ubuntu-jake:~/workspace$ ls -l BARAM-24.2.0
    total 6488
    -rwxr-xr-x  1 jake jake 3227792 Jun 11 10:56 BaramFlow
    -rwxr-xr-x  1 jake jake 3227792 Jun 11 10:56 BaramMesh
    -rw-r--r--  1 jake jake   99846 Jun 11 10:53 baramFlow.ico
    -rw-r--r--  1 jake jake   55174 Jun 11 10:53 baramMesh.ico
    -rw-r--r--  1 jake jake    3252 Jun 11 10:56 frozen_application_license.txt
    drwxr-xr-x 67 jake jake   12288 Jun 11 10:57 lib
    drwxr-xr-x  3 jake jake    4096 Jun 11 10:57 solvers
    jake@ubuntu-jake:~/workspace$
    ```

**Comment by jiban** [comment]
Hi Andrea,
It seems quite strange that *BaramFlow* is not working while *BaramMesh* is working well.
Now I'm suspecting if your global registry is corrupted.
Could you try it again after deleting or renaming the folders below? ( As you may know, `~` means your home directory )
( Please try it with the compressed-file version )
* `~/.BaramFlow`
* `~/.BaramMesh`

By the way, for your Friday trial on Windows, I'm preparing an updated package of v24.2.1.
Please use that version for you trial.
I will get it ready by the end of today.

-- Jake

**Comment by andprad74** [comment]
Hello Jake 
thanks for your support!

I don't have understood what you ask  to try.
In any case i made a fresh ubuntu 20.04 focal fossa virtual machine, 
i installed openmpi witht the command 
sudo apt install openmpi-bin
and with your file share here i must confirm that BaramMesh work well, BaramFlow no!

After i tested the Apptainer version it work but it's an old version like the windows version.
Thanks again.

Andrea

**Comment by jiban** [comment]
Hello Andrea,
Today I tried running BaramFlow and BaramMesh ( extracted from the compressed file I had sent to you a few days ago ) on fresh Ubuntu 20.04 focal fossa on Hyper-V virtual machine.
I installed *openmpi-bin* only with following command as you did.
```
sudo apt install openmpi-bin
```

The result is that **Both BaramFlow and BaramMesh are working well.**
I could not find any problem, and I hope your trial with fresh Ubuntu will work.

Following is my installation information
```
jake@jake-Virtual-Machine:~/BARAM-24.2.0$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
jake@jake-Virtual-Machine:~/BARAM-24.2.0$ ip addr show
```

By the way, updated BARAM installer for Windows is ready on [baramcfd](https://baramcfd.org/) page.
It's version is v24.2.1.

-- Jake

**Comment by andprad74** [comment]
Hello Jake 
yesterday i made the same test but with the Oracle Virtual Machine, fresh ubuntu 20.04.4 Focal Fossa but the result was different: Baramflow doesn't work.
I don't think that the problem can be related to the Oracle virtual machine but i can made some test with a different software.

Today i tested the v24.1.1 Win version on a new Hp Z2 workstation i9 13900k,i have some problem during the export after the boundary layer in the Baram Mesh but i must investigate.

I will let you informed of my tests.

by.
Andrea

**Comment by jiban** [comment]
Hello Andrea,
I hope you to try it with the latest version of 24.**2**.1.
Thank you.

-- Jake

**Comment by andprad74** [comment]
Hello,
regarding my problem witht the ubuntu version i solved after launch Baramflow with the command 
LC_NUMERIC="C" ./baramFlow.sh.
like explaned on the discussion 
https://github.com/nextfoam/baram/discussions/91.

Regarding the windows version 24.2.1 i made a test in comparison with 2023 R2 fluent, the mesh was the same made with fluent meshing but the results but sometime the results is very different.

I have found a lot of problem during the translation of the fluent mesh but at the end i solved.
Tha case was a multi- region heat transfer case.

By .
A

**Comment by jiban** [comment]
Hi Andrea,
I'm glad to hear that you finally come to use  BARAM without  an issue.
Please feel free to let me know any suggestion or features that you think useful.
Thank you.

Best regards,
Jake

**Comment by andprad74** [comment]
Thank you for everything.
Andrea
