### ISSUE TITLE
Edit window in Cell Zone Condition doesn't appear in BaramFlow v. 24.3.0

### ISSUE THREAD

**Issue by MTODC** [nextfoam/baram#98]
**Describe the bug**
The edit window in Cell Zone Conditions doesn't appear in BaramFlow v. 24.3.0, neither with double click nor with the edit button. I tried with the same mesh in v. 24.2.1 and it works perfectly.

**Desktop:**
 - OS: Windows 11
 - Version 24.3.0

**Comment by kdg5424** [comment]
Hello @MTODC .
This is Donggyu from NEXTFOAM.
Could you let me know detail? Or could you give your project folder?
This problem doesn't happen in my computer.

Thanks

**Comment by kdg5424** [comment]
Hello @MTODC.
The problem has appeared in our computer too.
We'll fix it very soon.
Thank you for your bug report

Donggyu kim

**Comment by jiban** [comment]
This has fixed in v24.3.1
